[17.05.2014 17:22:22.020464] [v 3.1.98.508] [tid 0x00001f6c] [sev 3] # a54c50d0 Application has been deployed
[17.05.2014 17:22:22.021465] [v 3.1.98.508] [tid 0x0000029c] [sev 2] WorkersManager - CreateFirst Worker.
[17.05.2014 17:23:46.054172] [v 3.1.98.508] [tid 0x00001394] [sev 2] WorkersManager - Ping Failed 
[17.05.2014 17:23:48.054949] [v 3.1.98.508] [tid 0x00001394] [sev 2] WorkersManager - Worker closed. #1
[17.05.2014 17:25:17.298286] [v 3.1.98.508] [tid 0x00001488] [sev 3] # a54c50d0 Restarting the application due to changes to file ;__init__.py
[17.05.2014 17:25:17.298286] [v 3.1.98.508] [tid 0x00001488] [sev 3] # a54c50d0 Application begin gracefulshutdown
[17.05.2014 17:25:17.298286] [v 3.1.98.508] [tid 0x00001488] [sev 2] WorkersManager - begin bracefulshutdown Application going to shutdown due to changed '__init__.py'
